### ISSUE TITLE
HomeAssistant 通过局域网开关 Win 电脑的方法

### ISSUE THREAD

**Issue by Daniel011011** [Daniel011011/CDN#9]
### 简介
旨在实现 Homeassistant 下通过 WOL 命令开启并且网络请求关闭局域网内的 Win 电脑，并把上述功能转化为一个 switch 开关。

### WOL
实现局域网内打开链接电源并且链接网线的电脑可以参考 少数派的这篇[文章](https://sspai.com/post/67003#!)

请在局域网内使用手机[ APP](https://apkpure.com/cn/search?q=wake+on+lane&t=app) 或者其他方式成功实现唤醒后继续

### 关机
需要借助第三方软件 [Airytec Switch Off](https://www.airytec.com/en/switch-off/)，安装完成后打开选项中如图1（使用github图床）选项。
 
![image](https://github.com/Daniel011011/CDN/assets/89135196/9f706d63-b7f0-49b5-ac48-0cc218889563)

并设置如图2，可以打开下面选项中的查看网页界面来确认是否能关机（注意关机前保存内容）

![image](https://github.com/Daniel011011/CDN/assets/89135196/5d9d1b51-17e4-498f-a111-bf52b594d059)

如果可以关机则复制网页中的关机地址形如 http://localhost:60/?action=System.Shutdown

修改localhost为你的电脑局域网地址

### Homeassistant 配置

添加如下内容到你的homeassistant [configuration.yaml](https://www.home-assistant.io/docs/configuration/)

win 电脑可以使用 [WinSCP](https://winscp.net/eng/index.php)

请注意把你的目标电脑 mac 和电脑局域网地址替换为你自己的

name处可自行修改
```
switch:
  - platform: wake_on_lan
    name: omen
    mac: 00:00:00:00:00:00
    turn_off:
      service: shell_command.turn_off_omen
shell_command:
  turn_off_omen: "curl -X GET http://192.168.31.44:60/?action=System.Shutdown" 
```

添加好后，如果没有问题重启 Homeassistant 后就可以在实体注册表里看见如下图的 switch

![image](https://github.com/Daniel011011/CDN/assets/89135196/ac24a38e-7ca4-44f7-8693-513d58510473)

后续可以添加进 HomeKit 等其他平台
